#!/usr/bin/env bash
# Script that tells a story based on the contents of the `/etc/passwd` file.

while IFS=':' read -r username password userID groupID info home shell; do
  echo "The user $username is part of the $groupID gang,"\
  "lives in $home and rides $shell."\
  "$userID's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
