#!/usr/bin/env bash
# Script that loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

b=0

while [ $b -lt 10 ]
do
  if [ $b -eq 3 ]
  then
    echo "bad luck"
  elif [ $b -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( b++ ))
done
